[package]
name = "cypher-rust"
version = "0.0.1"
authors = ["michel.barnich@cyphercrypto.io"]
edition = "2021"

[dependencies]
hyper = "^0.12"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
hyper-router = "^0.5"